import Vue from "vue";
import {
    Button,
    Select,
    Option,
    Menu,
    MenuItem,
    Row,
    Col,
    Tabs,
    TabPane,
    Form,
    FormItem,
    Input,
    DatePicker,
    TimePicker,
    Radio,
    RadioGroup,
    RadioButton,
    Checkbox,
    CheckboxButton,
    CheckboxGroup,
    Cascader,
    Upload,
    Icon,
    Link,
    Progress,
    Table,
    TableColumn,
    Slider,
    Popover
} from "element-ui";

Vue.use(Button);
Vue.use(Select);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Row);
Vue.use(Col);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Option);
Vue.use(DatePicker);
Vue.use(TimePicker);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(RadioButton);
Vue.use(Checkbox);
Vue.use(CheckboxButton);
Vue.use(CheckboxGroup);
Vue.use(Cascader);
Vue.use(Upload);
Vue.use(Icon);
Vue.use(Progress);
Vue.use(Link);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Slider);
Vue.use(Popover);
